### ISSUE TITLE
Provide a `IdbCursorWithValue::into_vec_values`

### ISSUE THREAD

**Issue by FirelightFlagboy** [Alorel/rust-indexed-db#39]
Currently `IdbCursorWithValue` provide `into_vec` method that return a `Vec` containing the `Key-Value` pair.

I would like to have something similar that only return the value.
Given the implentation of `into_vec` it seems doable to have something that return directly the `self.value()` in the mapper of `handle_into_vec`.

If it's fine for you, I could provide a PR

**Comment by Alorel** [comment]
Hey, I'm currently rewriting a lot of the crate so I'd avoid making new PRs in the meantime - I'll just take this into account when the PR for that is finally up. I only quickly glanced over the issue and source code just now so might be missing the mark here, but I think the issue might end up just getting closed as part of the redesign.

State of the library now:

- Essentially just turns Javascript requests with success/error events into Rust futures
- Still largely working with JS types
- Still feels like Rust bindings for a JS API

State I intend:

- Feels like an API written in and designed for Rust
- JS types only really exposed in catch-all type errors
- Integrates with `serde` for storing/reading objects instead of JS primitives
- Better integration with the Rust ecosystem, e.g. implementing streams for cursors

**Comment by Alorel** [comment]
@FirelightFlagboy Your request will be getting implemented indirectly - #40 is getting merged in the next couple of days unless I spot something horribly wrong and, with it, cursors will implement `Stream` and, by extension, [`TryStreamExt`](https://docs.rs/futures/0.3.31/futures/prelude/stream/trait.TryStreamExt.html) - it'll allow you to do any sort of manipulation you need.

**Comment by Alorel** [comment]
This issue has been included in [v0.6.0](https://github.com/Alorel/rust-indexed-db/releases/tag/v0.6.0) :tada:

\- Your friendly neighbourhood [:robot: semantic release bot](https://github.com/alorel-actions/semantic-release-lite)
